// This function was created with the assistance of GPT-4
// Much of the template for the code was generated by GPT-4
// Optimizations were developed after the template to streamline
// and make the code computationally fast.
//
// This implementation of polychoric correlations relies on numerical approximations
// for the inverse univariate normal CDF and bivariate normal CDF.
//
// Inverse Univariate Normal CDF: Beasley-Springer-Moro algorithm
//
// Bivariate Normal CDF: Genz's approximation (Genz, 2004), a double-precision
// extension of Drezner & Wesolowsky (1990) developed by Genz and Ge
//
// Optimization method: Newton-Raphson (Fisher scoring), with an exact-Hessian
// arcsin-reparameterized fallback to guarantee rho stays in (-1, 1)

// Headers to include
#include <math.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <stddef.h>
#include <R.h>
#include <Rinternals.h>
#include "polychoric_matrix.h" // Constants are defined here

// Constants in `bsm_inverse_cdf`
const double CONST_A[6] = {-39.69683028665376, 220.9460984245205, -275.928510446969, 138.357751867269, -30.66479806614716, 2.506628277459239};
const double CONST_B[5] = {-54.47609879822406, 161.5858368580409, -155.6989798598866, 66.80131188771972, -13.28068155288572};
const double CONST_C[6] = {-0.007784894002430293, -0.3223964580411365, -2.400758277161838, -2.549732539343734, 4.374664141464968, 2.938163982698783};
const double CONST_D[4] = {0.007784695709041462, 0.3224671290700398, 2.445134137142996, 3.754408661907416};

// Constants in `genz_bivariate_normal`
// Gauss-Legendre points/weights (positive half only) for N = 6, 12, and 20
const double GENZ_X6[3] = {-0.9324695142031522, -0.6612093864662647, -0.2386191860831970};
const double GENZ_W6[3] = {0.1713244923791705, 0.3607615730481384, 0.4679139345726904};
const double GENZ_X12[6] = {
  -0.9815606342467191, -0.9041172563704750, -0.7699026741943050,
  -0.5873179542866171, -0.3678314989981802, -0.1252334085114692
};
const double GENZ_W12[6] = {
  0.04717533638651177, 0.1069393259953183, 0.1600783285433464,
  0.2031674267230659, 0.2334925365383547, 0.2491470458134029
};
const double GENZ_X20[10] = {
  -0.9931285991850949, -0.9639719272779138, -0.9122344282513259,
  -0.8391169718222188, -0.7463319064601508, -0.6360536807265150,
  -0.5108670019508271, -0.3737060887154196, -0.2277858511416451,
  -0.07652652113349733
};
const double GENZ_W20[10] = {
  0.01761400713915212, 0.04060142980038694, 0.06267204833410906,
  0.08327674157670475, 0.1019301198172404, 0.1181945319615184,
  0.1316886384491766, 0.1420961093183821, 0.1491729864726037,
  0.1527533871307259
};

// Using the Beasley-Springer-Moro algorithm to perform `qnorm` function
double bsm_inverse_cdf(double probability){

  // Check for zero and one probabilities
  if(probability == 0) return(-INFINITY);
  if(probability == 1) return(INFINITY);

  // Initialize variables once
  double q, r, x;

  // (Not) lower tail flag
  bool not_lower_tail = probability >= 0.02425;

  // Determine region
  if(not_lower_tail && probability <= 0.97575){ // Middle

    // Define q
    q = probability - 0.50;

    // Define r
    r = q * q;

    // Define x
    x = ((((((CONST_A[0] * r + CONST_A[1]) * r + CONST_A[2]) * r + CONST_A[3]) * r + CONST_A[4]) * r + CONST_A[5]) * q) / (((((CONST_B[0] * r + CONST_B[1]) * r + CONST_B[2]) * r + CONST_B[3]) * r + CONST_B[4]) * r + 1);

  } else { // Ends

    // Define q
    if(not_lower_tail){
      q = sqrt(-2 * log(1 - probability));
    } else {
      q = sqrt(-2 * log(probability));
    }

    // Define x
    x = (((((CONST_C[0] * q + CONST_C[1]) * q + CONST_C[2]) * q + CONST_C[3]) * q + CONST_C[4]) * q + CONST_C[5]) / ((((CONST_D[0] * q + CONST_D[1]) * q + CONST_D[2]) * q + CONST_D[3]) * q + 1);

    // Check if the sign needs to be reversed
    if(not_lower_tail){
      x = -x;
    }

  }

  // Return x
  return x;

}

// Obtain joint frequency table
// Also accumulates the raw-code sums needed for a Pearson-correlation
// starting value (see `pearson_from_sums`) in the same pass over
// `input_data`, since `newton_raphson` needs a decent starting rho and
// otherwise a second full O(rows) scan would be required just for that.
// Fills the caller-provided (stack-allocated) `CUT x CUT` table in place --
// `CUT` bounds every category count in this package, so there is no need to
// heap-allocate a fresh table for every pair of variables
void joint_frequency_table(
    int* input_data, int rows, int i, int j, int* missing,
    double* sum_x, double* sum_y, double* sum_xx, double* sum_yy, double* sum_xy,
    int joint_frequency[CUT][CUT]
) {

  // Initialize X, Y, and iterator
  int X, Y, k;

  // Zero the table
  memset(joint_frequency, 0, sizeof(int) * CUT * CUT);

  // Pre-compute matrix offset for i and j
  int matrix_offset_i = i * rows;
  int matrix_offset_j = j * rows;

  // Initialize Pearson sums
  *sum_x = 0.0; *sum_y = 0.0; *sum_xx = 0.0; *sum_yy = 0.0; *sum_xy = 0.0;

  // Populate table
  for (k = 0; k < rows; k++) {

    // Obtain X and Y
    X = input_data[k + matrix_offset_i];
    Y = input_data[k + matrix_offset_j];

    // Check for missing data
    if(X != MISSING && Y != MISSING){

      joint_frequency[X][Y]++;

      // Accumulate Pearson sums
      *sum_x += X; *sum_y += Y;
      *sum_xx += (double) X * X;
      *sum_yy += (double) Y * Y;
      *sum_xy += (double) X * Y;

    }else{
      (*missing)++;
    }

  }

}

// Convert Pearson sums (from `joint_frequency_table`) into a starting value
// for `newton_raphson` -- unlike Brent's method, Newton-Raphson needs a
// reasonable starting point to converge quickly and reliably
static inline double pearson_from_sums(
    double sum_x, double sum_y, double sum_xx, double sum_yy, double sum_xy, int n
) {

  if(n < 2) return 0.0;

  double covariance = sum_xy / n - (sum_x / n) * (sum_y / n);
  double variance_x = sum_xx / n - (sum_x / n) * (sum_x / n);
  double variance_y = sum_yy / n - (sum_y / n) * (sum_y / n);

  if(variance_x <= 0 || variance_y <= 0) return 0.0;

  double r = covariance / sqrt(variance_x * variance_y);

  // Keep away from the boundary so the initial Newton step is well-defined
  if(r > 0.99) r = 0.99;
  if(r < -0.99) r = -0.99;

  return r;

}

// Update joint frequency table
/* Removes zero sum rows and columns and counts zero frequency cells */
// Fills the caller-provided (stack-allocated) `CUT x CUT` trimmed table in
// place; only the leading `cat_X x cat_Y` portion is meaningful on return
void update_joint_frequency(
    int joint_frequency_max[CUT][CUT], int* cat_X, int* cat_Y, int* zero_count,
    double joint_frequency_trim[CUT][CUT]
) {

  // Initialize iterators
  int i, j;

  // Count the non-zero rows and columns
  int non_zero_rows = 0;
  int non_zero_columns = 0;

  // Zero rows and columns (fully local to this function, no need to escape)
  bool zero_rows[CUT] = { false };
  bool zero_columns[CUT] = { false };

  // Loop over rows
  for(i = 0; i < CUT; i++) {

    // Initialize row and column sums
    int row_sum = 0;
    int column_sum = 0;

    // Loop over columns
    for(j = 0; j < CUT; j++) {

      // Increase sums
      row_sum += joint_frequency_max[i][j];
      column_sum += joint_frequency_max[j][i];

    }

    // Check for zero row sums
    if(row_sum == 0){
      zero_rows[i] = true;
    }else{
      non_zero_rows++;
    }

    // Check for zero column sums
    if(column_sum == 0){
      zero_columns[i] = true;
    }else{
      non_zero_columns++;
    }

  }

  // Initialize row count
  int row_count = 0;

  // Populate trimmed table
  for(i = 0; i < CUT; i++){

    // Check for zero row
    if(zero_rows[i]) {
      continue;
    }

    // Initialize column count
    int column_count = 0;

    for(j = 0; j < CUT; j++){

      // Check for zero column
      if(zero_columns[j]) {
        continue;
      }

      // Populate table
      joint_frequency_trim[row_count][column_count] = joint_frequency_max[i][j];

      // Increase zero count
      if(joint_frequency_max[i][j] == 0){
        (*zero_count)++;
      }

      // Increase column
      column_count++;

    }

    // Increase row
    row_count++;

  }

  // Assign non-zero values to categories
  *cat_X = non_zero_rows;
  *cat_Y = non_zero_columns;

}

// Function to compute probabilities
static inline void compute_probabilities(double* frequency, int cat, double cases) {

  for(int k = 0; k < cat; k++) {
    frequency[k] = frequency[k] / cases;
  }

}

// Function to compute cumulative sums
static inline void compute_cumulative(double* frequency, int cat) {

  for (int k = 1; k < cat; k++) {
    frequency[k] += frequency[k - 1];
  }

}

// Function to compute thresholds
static inline void compute_thresholds(double* frequency, int cat, double* threshold) {

  for (int k = 0; k < cat; k++) {
    threshold[k] = bsm_inverse_cdf(frequency[k]);
  }

}

// Define structure for return values
// All arrays are embedded (fixed-size, `CUT`-bounded) rather than pointers
// to heap memory: only the leading `cat_X`/`cat_Y` portion of each is
// meaningful, and returning the struct by value means every pair of
// variables is processed without a single malloc/free
struct ThresholdsResult {
  double joint_frequency[CUT][CUT];
  double threshold_X[CUT];
  double threshold_Y[CUT];
  double probability_X[CUT];
  double probability_Y[CUT];
  int cat_X;
  int cat_Y;
  double cases;
  double pearson_start;
};

// Compute thresholds
struct ThresholdsResult thresholds(int* input_data, int rows, int i, int j, int empty_method, double empty_value) {

  // Initialize iterators
  int k, l;

  // Initialize missing
  int missing = 0;

  // Obtain joint frequency table (and, in the same pass over `input_data`,
  // the raw-code Pearson sums used as a Newton-Raphson starting value).
  // This raw (untrimmed) table never escapes this function, so it lives on
  // the stack
  int raw_table[CUT][CUT];
  double sum_x, sum_y, sum_xx, sum_yy, sum_xy;
  joint_frequency_table(
    input_data, rows, i, j, &missing, &sum_x, &sum_y, &sum_xx, &sum_yy, &sum_xy, raw_table
  );
  double pearson_start_value = pearson_from_sums(sum_x, sum_y, sum_xx, sum_yy, sum_xy, rows - missing);

  // Initialize categories
  int cat_X = 0;
  int cat_Y = 0;

  // Initialize zero count
  int zero_count = 0;

  // Update joint frequency table (remove zero rows), writing directly into
  // the (stack-allocated, embedded) result struct -- also the safe default
  // ({0}) returned on the (unreachable-after-`Rf_error`) validation paths below
  struct ThresholdsResult result = {0};
  update_joint_frequency(raw_table, &cat_X, &cat_Y, &zero_count, result.joint_frequency);

  // Initialize added value
  double added_value = 0.0;
  double added_sum = 0.0;

  // Check for zero cells
  if(zero_count > 0){

    // If there are zero cells, check method
    if(empty_method != 0){

      // Flag for empty cell methods
      bool zero = empty_method == 1;
      // bool all = empty_method == 2;

      // Check for one over method
      if(empty_value > 1.0){
        added_value = 1 / (double) (cat_X * cat_Y); // needs conversion to double before division
      }else{
        added_value = empty_value;
      }

      // Update joint frequency table
      for (k = 0; k < cat_X; k++) {
        for(l = 0; l < cat_Y; l++){

          // Check for method
          if(zero && result.joint_frequency[k][l] == 0){
            result.joint_frequency[k][l] += added_value;
            added_sum += added_value;
          } else { // if(all){
            result.joint_frequency[k][l] += added_value;
            added_sum += added_value;
          }

        }
      }

    }

  }

  // Validate category sizes before allocation
  if ((cat_X <= 0) || (cat_X > CUT)) {
      Rf_error("Invalid category sizes for variable X. Terminating...");
      return result; // unreachable (`Rf_error` longjmps), kept for clarity
  }

   // Validate category sizes before allocation
  if ((cat_Y <= 0) || (cat_Y > CUT)) {
      Rf_error("Invalid category sizes for variable Y. Terminating...");
      return result; // unreachable (`Rf_error` longjmps), kept for clarity
  }

  /* Above code seems to be OK with CRAN checks */

  // Obtain frequencies (accumulated directly into the result struct's
  // probability arrays, later transformed into cumulative probabilities
  // and thresholds in place)
  for(k = 0; k < cat_X; k++) {
    for(l = 0; l < cat_Y; l++) {
      result.probability_X[k] += result.joint_frequency[k][l];
      result.probability_Y[l] += result.joint_frequency[k][l];
    }
  }

  // Compute cases
  double cases = rows - missing + added_sum;

  // Convert frequencies to probabilities
  compute_probabilities(result.probability_X, cat_X, cases);
  compute_probabilities(result.probability_Y, cat_Y, cases);

  // Convert probabilities to cumulative sums
  compute_cumulative(result.probability_X, cat_X);
  compute_cumulative(result.probability_Y, cat_Y);

  // Obtain thresholds
  compute_thresholds(result.probability_X, cat_X, result.threshold_X);
  compute_thresholds(result.probability_Y, cat_Y, result.threshold_Y);

  result.cat_X = cat_X;
  result.cat_Y = cat_Y;
  result.cases = cases;
  result.pearson_start = pearson_start_value;

  // Return
  return result;
}

// Univariate normal CDF
// Implements Genz's `MVPHI` via the standard library's `erfc`: Phi(z) =
// 0.5 * erfc(-z / sqrt(2)). Correct at the +-Inf limits (erfc saturates to
// 0/2 well before overflowing) without a separate early-return, and is
// roughly 3x faster than a from-scratch Chebyshev expansion (e.g.
// Schonfelder, 1978) since it's backed by a tuned libm implementation
static inline double genz_normal_cdf(double z) {

  return 0.5 * erfc(-z * 0.70710678118654752440); // 1 / sqrt(2)

}

// Precomputed, rho-only derived quantities shared by `genz_bivariate_normal`,
// `bivariate_normal_density`, and `bivariate_normal_density_derivative`.
// Within one Newton iteration, rho is fixed while these three functions are
// each called once per corner of a `(cat_X + 1) x (cat_Y + 1)` grid -- so
// building this once per iteration (see `make_rho_context`) avoids
// redoing the same `asin`/`sqrt`/quadrature-rule-selection work at every
// single grid point
struct RhoContext {
  double rho;
  double rho_abs;
  bool near_boundary; // rho_abs >= GENZ_COR_MAX

  // Used when !near_boundary (`genz_bivariate_normal`'s main branch)
  double asr;         // asin(rho)
  const double* nodes;
  const double* weights;
  int points;

  // Used when near_boundary (`genz_bivariate_normal`'s tail branch)
  bool negative;       // rho < 0
  double as;           // (1 - rho) * (1 + rho)
  double a;             // sqrt(as)
  double a_half;       // a / 2

  // Used by `bivariate_normal_density(_derivative)`
  double c;            // 1 - rho^2
  double sqrt_c;
  double c2;           // c^2
};

static inline struct RhoContext make_rho_context(double rho) {

  struct RhoContext ctx;
  ctx.rho = rho;
  ctx.rho_abs = fabs(rho);
  ctx.near_boundary = ctx.rho_abs >= GENZ_COR_MAX;

  if(!ctx.near_boundary) {

    ctx.asr = asin(rho);

    // Select Gauss-Legendre rule based on |rho|
    if(ctx.rho_abs < 0.3) {
      ctx.nodes = GENZ_X6; ctx.weights = GENZ_W6; ctx.points = 3;
    } else if(ctx.rho_abs < 0.75) {
      ctx.nodes = GENZ_X12; ctx.weights = GENZ_W12; ctx.points = 6;
    } else {
      ctx.nodes = GENZ_X20; ctx.weights = GENZ_W20; ctx.points = 10;
    }

  } else {

    ctx.negative = rho < 0.0;
    ctx.as = (1 - rho) * (1 + rho);
    ctx.a = sqrt(ctx.as);
    ctx.a_half = ctx.a / 2;

  }

  ctx.c = 1 - rho * rho;
  ctx.sqrt_c = sqrt(ctx.c);
  ctx.c2 = ctx.c * ctx.c;

  return ctx;

}

// Bivariate normal CDF
// Implements Genz's `MVBVU` (Genz & Ge's double-precision extension of
// Drezner & Wesolowsky, 1990), which uses a variable-order (6-, 12-, or
// 20-point) Gauss-Legendre rule depending on |rho| and an extended series
// correction for |rho| close to 1, giving higher accuracy than the fixed
// 5-point rule it replaces (Genz, 2004, Statistics and Computing, 14, 251-260)
// Translated from Fortran (TVPACK, `MVBVU`): https://github.com/cran/pbivnorm/blob/master/src/pbivnorm.f
//
// `genz_bivariate_normal(h1, h2, ctx, p1, p2)` returns Phi_2(h1, h2; rho),
// obtained via `MVBVU(-h1, -h2, rho)` and simplified using the identity
// Phi_2(h1, h2; rho) = P(X > -h1, Y > -h2), with `p1 = Phi(h1)` and
// `p2 = Phi(h2)` supplied by the caller (already known exactly from the
// empirical cumulative frequencies) rather than recomputed. `ctx` bundles
// every quantity that depends on rho alone (see `RhoContext`).
// `static inline` (like the density functions below) so the compiler can
// fully inline it at its two call sites in `newton_raphson`/
// `newton_raphson_arcsin`, keeping `ctx`'s fields in registers across the
// grid loop instead of re-reading them through the pointer on every call
static inline double genz_bivariate_normal(double h1, double h2, const struct RhoContext* ctx, double p1, double p2) {

  // Check for infinities
  if(h1 == -INFINITY || h2 == -INFINITY) return(0.0);
  if(h1 == INFINITY) return(p2);
  if(h2 == INFINITY) return(p1);

  double rho = ctx->rho;

  // Obtain h*k
  double hk = h1 * h2;

  // Initialize probability
  double bv = 0.0;

  // Check for correlation lower than maximum
  if(!ctx->near_boundary) {

    // Obtain h12
    double h12 = (h1 * h1 + h2 * h2) / 2;
    double asr = ctx->asr;

    const double* nodes = ctx->nodes;
    const double* weights = ctx->weights;
    int points = ctx->points;

    // Gauss-Legendre quadrature over the correlation "arc"
    for(int i = 0; i < points; i++) {
      double sn = sin(asr * (nodes[i] + 1) / 2);
      bv += weights[i] * exp((sn * hk - h12) / (1 - sn * sn));
      sn = sin(asr * (-nodes[i] + 1) / 2);
      bv += weights[i] * exp((sn * hk - h12) / (1 - sn * sn));
    }

    // Finalize probability
    bv = bv * asr / (2 * TWO_PI) + p1 * p2;

  } else { // At or beyond the maximum correlation (0.925)

    // Local (possibly sign-flipped) versions of h2 and h*k
    double k = h2;
    double hk_local = hk;

    // Reverse sign for negative correlation
    if(ctx->negative) {
      k = -k;
      hk_local = -hk_local;
    }

    // Check for correlation less than 1
    if(ctx->rho_abs < 1.0) {

      // Set up variables
      double as = ctx->as;
      double a = ctx->a;
      double bs = (h1 - k) * (h1 - k);
      double c = (4 - hk_local) / 8;
      double d = (12 - hk_local) / 16;

      // Compute initial probability
      bv = a * exp(-(bs / as + hk_local) / 2) *
        (1 - c * (bs - as) * (1 - d * bs / 5) / 3 + c * d * as * as / 5);

      // Add tail correction
      if(hk_local > GENZ_HK_MIN) {
        double b = sqrt(bs);
        bv -= exp(-hk_local / 2) * SQRT_TWO_PI * genz_normal_cdf(-b / a) * b *
          (1 - c * bs * (1 - d * bs / 5) / 3);
      }

      // Beyond the maximum correlation always uses the 20-point rule
      double a_half = ctx->a_half;
      for(int i = 0; i < 10; i++) {

        double xs = (a_half * (GENZ_X20[i] + 1)) * (a_half * (GENZ_X20[i] + 1));
        double rs = sqrt(1 - xs);
        bv += a_half * GENZ_W20[i] * (
          exp(-bs / (2 * xs) - hk_local / (1 + rs)) / rs -
          exp(-(bs / xs + hk_local) / 2) * (1 + c * xs * (1 + d * xs))
        );

        xs = as * (-GENZ_X20[i] + 1) * (-GENZ_X20[i] + 1) / 4;
        rs = sqrt(1 - xs);
        bv += a_half * GENZ_W20[i] * exp(-(bs / xs + hk_local) / 2) * (
          exp(-hk_local * (1 - rs) / (2 * (1 + rs))) / rs -
          (1 + c * xs * (1 + d * xs))
        );

      }

      bv = -bv / TWO_PI;

    }

    // Adjust for correlation sign
    if(rho > 0) {
      bv += fmin(p1, p2);
    } else {
      bv = -bv + fmax(0.0, p1 + p2 - 1);
    }

  }

  // Return probability
  return bv;

}

// Expand `cat` category thresholds/probabilities into their `cat + 1` cell
// *boundaries* (including the -Inf/+Inf outer edges), e.g. for thresholds
// {t0, t1} (cat = 3): boundary = {-Inf, t0, t1, +Inf}. Cell `index`
// (0-indexed) then spans [boundary[index], boundary[index + 1]]. Materializing
// these once lets a `(cat_X + 1) x (cat_Y + 1)` grid of corner values be
// built and reused across all `cat_X * cat_Y` cells, instead of recomputing
// each corner up to 4 times (once per adjacent cell)
static inline void compute_boundaries(
    double* threshold, double* probability, int cat,
    double* boundary, double* boundary_p
) {

  boundary[0] = -INFINITY;
  boundary_p[0] = 0.0;

  for(int k = 1; k < cat; k++) {
    boundary[k] = threshold[k - 1];
    boundary_p[k] = probability[k - 1];
  }

  boundary[cat] = INFINITY;
  boundary_p[cat] = 1.0;

}


// Bivariate normal density (standard, mean 0, variance 1)
// Used for the score (gradient) of the polychoric log-likelihood with
// respect to rho. `ctx->c`/`ctx->sqrt_c` (1 - rho^2 and its square root)
// are precomputed once per iteration rather than once per grid corner
static inline double bivariate_normal_density(const struct RhoContext* ctx, double x, double y) {

  // Density is zero in the limit as either margin goes to infinity
  if(!isfinite(x) || !isfinite(y)) return 0.0;

  // Obtain the quadratic form
  double q = x * x + y * y - 2 * ctx->rho * x * y;

  // Return density
  return exp(-q / (2 * ctx->c)) / (TWO_PI * ctx->sqrt_c);

}

// Derivative of the bivariate normal density with respect to rho
// Used for the exact Hessian in `newton_raphson_arcsin`
static inline double bivariate_normal_density_derivative(const struct RhoContext* ctx, double x, double y) {

  if(!isfinite(x) || !isfinite(y)) return 0.0;

  double rho = ctx->rho;
  double c = ctx->c;

  // Obtain the quadratic form
  double q = x * x + y * y - 2 * rho * x * y;
  double density = exp(-q / (2 * c)) / (TWO_PI * ctx->sqrt_c);

  // d(density)/d(rho) = density * [c * (rho + x * y) - rho * q] / c^2
  return density * (c * (rho + x * y) - rho * q) / ctx->c2;

}

// Forward declaration: `newton_raphson`'s bounded fallback, defined below
double newton_raphson_arcsin(
    double start, double joint_frequency[][CUT],
    double* threshold_X, double* threshold_Y,
    double* probability_X, double* probability_Y,
    int cat_X, int cat_Y, double cases
);

// Newton-Raphson (Fisher scoring) on the raw rho scale
// Falls back to `newton_raphson_arcsin` whenever an unconstrained step
// would leave (-1, 1)
double newton_raphson(
    double start, double joint_frequency[][CUT],
    double* threshold_X, double* threshold_Y,
    double* probability_X, double* probability_Y,
    int cat_X, int cat_Y, double cases
) {

  double rho = start;

  // Cell boundaries (thresholds plus the -Inf/+Inf outer edges) and their
  // marginal probabilities, built once since they do not depend on rho
  double boundary_X[CUT + 1], boundary_pX[CUT + 1];
  double boundary_Y[CUT + 1], boundary_pY[CUT + 1];
  compute_boundaries(threshold_X, probability_X, cat_X, boundary_X, boundary_pX);
  compute_boundaries(threshold_Y, probability_Y, cat_Y, boundary_Y, boundary_pY);

  for(int iter = 0; iter < NEWTON_MAX_ITER; iter++) {

    // Precompute every rho-only derived quantity once for this iteration
    // (rho is fixed across the whole grid below)
    struct RhoContext ctx = make_rho_context(rho);

    // Evaluate the bivariate CDF and density once per grid corner (rather
    // than once per cell corner, up to 4x redundant) and difference them
    // into per-cell values below
    double cdf_grid[CUT + 1][CUT + 1];
    double density_grid[CUT + 1][CUT + 1];

    for(int a = 0; a <= cat_X; a++) {
      for(int b = 0; b <= cat_Y; b++) {
        cdf_grid[a][b] = genz_bivariate_normal(
          boundary_X[a], boundary_Y[b], &ctx, boundary_pX[a], boundary_pY[b]
        );
        density_grid[a][b] = bivariate_normal_density(&ctx, boundary_X[a], boundary_Y[b]);
      }
    }

    double gradient = 0.0;
    double information = 0.0;

    for(int i = 0; i < cat_X; i++) {
      for(int j = 0; j < cat_Y; j++) {

        // Cell probability (bivariate normal CDF over the cell rectangle)
        double probability = cdf_grid[i + 1][j + 1] - cdf_grid[i][j + 1] -
                              cdf_grid[i + 1][j] + cdf_grid[i][j];

        if(probability < NEWTON_PROB_MIN) probability = NEWTON_PROB_MIN;

        // d(cell probability)/d(rho), via the bivariate normal density
        double density = density_grid[i + 1][j + 1] - density_grid[i][j + 1] -
                          density_grid[i + 1][j] + density_grid[i][j];

        // Gradient of the negative log-likelihood (per observation) and its
        // Fisher information approximation (expected outer product of the score)
        gradient -= joint_frequency[i][j] / probability * density / cases;
        information += density * density / probability;

      }
    }

    // Cap the step so a large gradient / tiny information (near the
    // boundary or in sparse cells) cannot fling rho far from its current
    // value in a single iteration -- undamped steps can overshoot into a
    // different (spurious) basin of attraction entirely
    double step = gradient / information;
    if(step > NEWTON_MAX_STEP) step = NEWTON_MAX_STEP;
    if(step < -NEWTON_MAX_STEP) step = -NEWTON_MAX_STEP;

    double proposed = rho - step;

    // Fall back to the bounded, exact-Hessian arcsin parameterization
    // whenever the (capped) step would leave (-1, 1)
    if(proposed >= 1.0 || proposed <= -1.0) {
      return newton_raphson_arcsin(
        start, joint_frequency, threshold_X, threshold_Y,
        probability_X, probability_Y, cat_X, cat_Y, cases
      );
    }

    rho = proposed;

    if(gradient * gradient < NEWTON_TOL) break;

  }

  return rho;

}

// Newton-Raphson on theta = asin(rho), using the exact Hessian
// (`bivariate_normal_density_derivative`). Guarantees rho stays in (-1, 1)
// for any real theta, so this also serves as the bounded fallback for
// `newton_raphson`
double newton_raphson_arcsin(
    double start, double joint_frequency[][CUT],
    double* threshold_X, double* threshold_Y,
    double* probability_X, double* probability_Y,
    int cat_X, int cat_Y, double cases
) {

  double theta = asin(start);
  double rho = start;
  double cos_theta = cos(theta);

  // Cell boundaries (thresholds plus the -Inf/+Inf outer edges) and their
  // marginal probabilities, built once since they do not depend on rho
  double boundary_X[CUT + 1], boundary_pX[CUT + 1];
  double boundary_Y[CUT + 1], boundary_pY[CUT + 1];
  compute_boundaries(threshold_X, probability_X, cat_X, boundary_X, boundary_pX);
  compute_boundaries(threshold_Y, probability_Y, cat_Y, boundary_Y, boundary_pY);

  for(int iter = 0; iter < NEWTON_MAX_ITER; iter++) {

    // Precompute every rho-only derived quantity once for this iteration
    // (rho is fixed across the whole grid below)
    struct RhoContext ctx = make_rho_context(rho);

    // Evaluate the CDF, density, and density derivative once per grid
    // corner (rather than once per cell corner, up to 4x redundant) and
    // difference them into per-cell values below
    double cdf_grid[CUT + 1][CUT + 1];
    double density_grid[CUT + 1][CUT + 1];
    double derivative_grid[CUT + 1][CUT + 1];

    for(int a = 0; a <= cat_X; a++) {
      for(int b = 0; b <= cat_Y; b++) {
        cdf_grid[a][b] = genz_bivariate_normal(
          boundary_X[a], boundary_Y[b], &ctx, boundary_pX[a], boundary_pY[b]
        );
        density_grid[a][b] = bivariate_normal_density(&ctx, boundary_X[a], boundary_Y[b]);
        derivative_grid[a][b] = bivariate_normal_density_derivative(&ctx, boundary_X[a], boundary_Y[b]);
      }
    }

    double gradient = 0.0;
    double hessian = 0.0;

    for(int i = 0; i < cat_X; i++) {
      for(int j = 0; j < cat_Y; j++) {

        double probability = cdf_grid[i + 1][j + 1] - cdf_grid[i][j + 1] -
                              cdf_grid[i + 1][j] + cdf_grid[i][j];

        if(probability < NEWTON_PROB_MIN) probability = NEWTON_PROB_MIN;

        double density = density_grid[i + 1][j + 1] - density_grid[i][j + 1] -
                          density_grid[i + 1][j] + density_grid[i][j];

        double density_derivative = derivative_grid[i + 1][j + 1] - derivative_grid[i][j + 1] -
                                     derivative_grid[i + 1][j] + derivative_grid[i][j];

        // Chain rule onto theta (rho = sin(theta), d(rho)/d(theta) = cos(theta))
        double density_theta = density * cos_theta;
        double curvature = density_derivative * cos_theta * cos_theta - density * rho;

        gradient -= joint_frequency[i][j] / probability * density_theta / cases;
        hessian += joint_frequency[i][j] *
          (density_theta * density_theta - probability * curvature) /
          (probability * probability) / cases;

      }
    }

    // Cap the theta step -- without damping, an ill-conditioned Hessian
    // (which happens near the boundary, exactly where this fallback is
    // invoked) can send theta wrapping across multiple periods of sin(),
    // landing on a spurious stationary point instead of the true MLE
    double dtheta = gradient / hessian;
    if(dtheta > NEWTON_MAX_STEP) dtheta = NEWTON_MAX_STEP;
    if(dtheta < -NEWTON_MAX_STEP) dtheta = -NEWTON_MAX_STEP;

    theta -= dtheta;

    // Keep theta within its principal branch: every rho in (-1, 1) is
    // already reached by theta in (-pi/2, pi/2), so restricting it here
    // both avoids the periodic wraparound above and keeps rho strictly
    // inside (-1, 1) -- rho = +-1 makes 1 - rho^2 = 0, a division by zero
    // in `bivariate_normal_density`
    if(theta > NEWTON_THETA_MAX) theta = NEWTON_THETA_MAX;
    if(theta < -NEWTON_THETA_MAX) theta = -NEWTON_THETA_MAX;

    rho = sin(theta);

    if(gradient * gradient < NEWTON_TOL) break;

    cos_theta = cos(theta);

  }

  return rho;

}

// Compute polychoric correlation
double polychoric(int* input_data, int rows, int i, int j, int empty_method, double empty_value) {

  // Obtain joint frequency table, probability_X, probability_Y, and a
  // Newton-Raphson starting value (Pearson correlation of the raw codes)
  // from the thresholds function
  struct ThresholdsResult thresholds_result = thresholds(input_data, rows, i, j, empty_method, empty_value);

  // Perform optimization (no memory to free afterward: `ThresholdsResult`'s
  // arrays are stack-embedded, not heap-allocated)
  double rho_optimum = newton_raphson(
    thresholds_result.pearson_start, thresholds_result.joint_frequency,
    thresholds_result.threshold_X, thresholds_result.threshold_Y,
    thresholds_result.probability_X, thresholds_result.probability_Y,
    thresholds_result.cat_X, thresholds_result.cat_Y, thresholds_result.cases
  );

  // Return
  return rho_optimum;

}

// The updated polychoric_correlation_matrix function
void polychoric_correlation_matrix(
    int* input_data, int rows, int cols,
    int empty_method, double empty_value, double* polychoric_matrix
) {

  // Initialize iterators
  int i, j;
  double correlation;
  int matrix_offset[cols];
  matrix_offset[0] = 0;

  // Initialize offset
  for(i = 1; i < cols; i++){
    matrix_offset[i] = matrix_offset[i - 1] + cols;
  }

  // Perform polychoric correlations over the input_matrix
  for (i = 0; i < cols; i++) {

    // Fill diagonal
    polychoric_matrix[matrix_offset[i] + i] = 1;

    // Loop over other variables
    for (j = i + 1; j < cols; j++) {

      // Compute correlation
      correlation = polychoric(
        input_data, rows, i, j, empty_method, empty_value
      );

      // Add to matrix
      polychoric_matrix[matrix_offset[i] + j] = correlation;

      // Fill opposite of triangle
      polychoric_matrix[matrix_offset[j] + i] = correlation;

    }
  }

}

// Interface with R
SEXP r_polychoric_correlation_matrix(
    SEXP r_input_matrix, SEXP r_empty_method,
    SEXP r_empty_value, SEXP r_rows, SEXP r_cols
) {

  // Initialize columns
  int cols = INTEGER(r_cols)[0];

  // Initialize R result
  SEXP r_result = PROTECT(allocVector(REALSXP, cols * cols));
  double* c_result = REAL(r_result);

  // Call the C function
  polychoric_correlation_matrix(
    INTEGER(r_input_matrix), INTEGER(r_rows)[0], cols,
    INTEGER(r_empty_method)[0], REAL(r_empty_value)[0],
    c_result // Pass the pointer directly to the C function
  );

  // Free R result
  UNPROTECT(1);

  // Return R result
  return r_result;

}
